target:
	gcc assignment_2_1.c -o prob_1 -lpthread
	gcc assignment_2_3.c_4 -o prob_2 -lpthread
	gcc assignment_2_4(client).c_1 -o prob_3a -lrt
	gcc assignment_2_4.(server).c -o prob_3b -lrt
	gcc assignment_2_5.c(receiver) -o prob_4a -lrt
	gcc assignment_2_5.c(sender) -o prob_4b -lrt
